package main

// StarterPaints is an optional starting set, offered when the paint rack is
// empty so there's no need to type three dozen entries by hand.
var StarterPaints = []Paint{
	{Name: "Abaddon Black", Brand: "Citadel", Type: "Base", Hex: "#231f20"},
	{Name: "Corax White", Brand: "Citadel", Type: "Base", Hex: "#f3f3ef"},
	{Name: "Macragge Blue", Brand: "Citadel", Type: "Base", Hex: "#0d407f"},
	{Name: "Calgar Blue", Brand: "Citadel", Type: "Layer", Hex: "#2f6bb0"},
	{Name: "Mephiston Red", Brand: "Citadel", Type: "Base", Hex: "#8f1216"},
	{Name: "Evil Sunz Scarlet", Brand: "Citadel", Type: "Layer", Hex: "#c1272d"},
	{Name: "Caliban Green", Brand: "Citadel", Type: "Base", Hex: "#00401a"},
	{Name: "Warpstone Glow", Brand: "Citadel", Type: "Layer", Hex: "#1e7b33"},
	{Name: "Death Guard Green", Brand: "Citadel", Type: "Base", Hex: "#7f8f4e"},
	{Name: "Zandri Dust", Brand: "Citadel", Type: "Base", Hex: "#b5a469"},
	{Name: "Ushabti Bone", Brand: "Citadel", Type: "Layer", Hex: "#c8bf8c"},
	{Name: "Screaming Skull", Brand: "Citadel", Type: "Layer", Hex: "#d9d6b0"},
	{Name: "Rakarth Flesh", Brand: "Citadel", Type: "Base", Hex: "#b4aa9a"},
	{Name: "Bugman's Glow", Brand: "Citadel", Type: "Base", Hex: "#804d45"},
	{Name: "Cadian Fleshtone", Brand: "Citadel", Type: "Layer", Hex: "#c07f68"},
	{Name: "Kislev Flesh", Brand: "Citadel", Type: "Layer", Hex: "#d9a97e"},
	{Name: "Leadbelcher", Brand: "Citadel", Type: "Base", Hex: "#8a8d8f"},
	{Name: "Ironbreaker", Brand: "Citadel", Type: "Layer", Hex: "#a1a6a9"},
	{Name: "Retributor Armour", Brand: "Citadel", Type: "Base", Hex: "#c08a2d"},
	{Name: "Auric Armour Gold", Brand: "Citadel", Type: "Layer", Hex: "#e0a949"},
	{Name: "Mechanicus Standard Grey", Brand: "Citadel", Type: "Base", Hex: "#3f4b4e"},
	{Name: "Dawnstone", Brand: "Citadel", Type: "Layer", Hex: "#6f7573"},
	{Name: "Rhinox Hide", Brand: "Citadel", Type: "Base", Hex: "#4b3435"},
	{Name: "Mournfang Brown", Brand: "Citadel", Type: "Layer", Hex: "#7a4a24"},
	{Name: "Nuln Oil", Brand: "Citadel", Type: "Shade", Hex: "#141414"},
	{Name: "Agrax Earthshade", Brand: "Citadel", Type: "Shade", Hex: "#3b2f24"},
	{Name: "Seraphim Sepia", Brand: "Citadel", Type: "Shade", Hex: "#8a6a32"},
	{Name: "Carroburg Crimson", Brand: "Citadel", Type: "Shade", Hex: "#6d1526"},
	{Name: "Drakenhof Nightshade", Brand: "Citadel", Type: "Shade", Hex: "#1d3a5c"},
	{Name: "Nurgle's Rot", Brand: "Citadel", Type: "Technical", Hex: "#8f9a4a"},
	{Name: "Blood for the Blood God", Brand: "Citadel", Type: "Technical", Hex: "#6c0f11"},
	{Name: "Astrogranite", Brand: "Citadel", Type: "Technical", Hex: "#6b6b68"},
	{Name: "Templar Grey", Brand: "Vallejo", Type: "Base", Hex: "#4a5560"},
	{Name: "Wolf Grey", Brand: "Vallejo", Type: "Layer", Hex: "#8394a8"},
	{Name: "Matt Varnish", Brand: "Army Painter", Type: "Technical", Hex: "#cfd6dd"},
	{Name: "Strong Tone", Brand: "Army Painter", Type: "Wash", Hex: "#4a3520"},
}
